# vim:fileencoding=utf-8:foldmethod=marker

# Gruvbox Dark theme for Yazi (Medium Contrast)
# Based on https://github.com/morhetz/gruvbox

# : Manager {{{
[manager]
cwd = { fg = "#458588" }  # neutral_blue

# Main colors
fg = "#ebdbb2"  # light1
bg = "#282828"  # dark0
preview_fg = "#ebdbb2"  # light1
preview_bg = "#282828"  # dark0

# Hovered
hovered = { fg = "#282828", bg = "#458588" }  # dark0, neutral_blue
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#b8bb26", italic = true }   # neutral_green
find_position = { fg = "#fe8019", bg = "reset", italic = true }  # neutral_orange

# Marker
marker_selected = { fg = "#b8bb26", bg = "#b8bb26" }  # neutral_green
marker_copied = { fg = "#b8bb26", bg = "#b8bb26" }    # neutral_green
marker_cut = { fg = "#fb4934", bg = "#fb4934" }        # neutral_red

# Tab
tab_active = { fg = "#282828", bg = "#504945" }    # dark0, dark4
tab_inactive = { fg = "#a89984", bg = "#3c3836" }  # light4, dark1
tab_width = 1

# Border
border_symbol = "│"
border_style = { fg = "#665c54" }  # dark3

# Highlighting
syntect_theme = "~/.config/yazi/Gruvbox-Dark.tmTheme"
# : }}}

# : Status {{{
[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#3c3836", bg = "#3c3836" }  # dark1

# Progress
progress_label = { fg = "#ebdbb2", bold = true }    # light1
progress_normal = { fg = "#504945", bg = "#3c3836" }  # dark4, dark1
progress_error = { fg = "#fb4934", bg = "#3c3836" }    # neutral_red, dark1

# Permissions
permissions_t = { fg = "#504945" }  # dark4
permissions_r = { fg = "#b8bb26" }  # neutral_green
permissions_w = { fg = "#fb4934" }  # neutral_red
permissions_x = { fg = "#b8bb26" }  # neutral_green
permissions_s = { fg = "#665c54" }  # dark3

# Bar
bar_symbol = "█"
bar_style = { fg = "#504945", bg = "#3c3836" }  # dark4, dark1

# Separator symbols
separator_style = { fg = "#504945", bg = "#3c3836" }  # dark4, dark1
separator_symbol = ""
separator_front_symbol = ""

# Owner
owner = { fg = "#ebdbb2" }  # light1
group = { fg = "#928374" }  # gray

# Count
count = { fg = "#ebdbb2" }  # light1
# : }}}

# : Mode {{{
[mode]
normal_main = { fg = "#282828", bg = "#a89984", bold = true }  # dark0, light4
normal_alt = { fg = "#282828", bg = "#a89984", bold = true }    # dark0, light4

select_main = { fg = "#282828", bg = "#b8bb26", bold = true }  # dark0, neutral_green
select_alt = { fg = "#282828", bg = "#b8bb26", bold = true }    # dark0, neutral_green

unset_main = { fg = "#282828", bg = "#d3869b", bold = true }  # dark0, neutral_purple
unset_alt = { fg = "#282828", bg = "#d3869b", bold = true }    # dark0, neutral_purple
# : }}}

# : Input {{{
[input]
border = { fg = "#bdae93" }  # light3
title = {}
value = {}
selected = { reversed = true }
# : }}}

# : Select {{{
[select]
border = { fg = "#504945" }    # dark4
active = { fg = "#fe8019" }     # neutral_orange
inactive = {}
# : }}}

# : Tasks {{{
[tasks]
border = { fg = "#504945" }  # dark4
title = {}
hovered = { underline = true }
# : }}}

# : Which {{{
[which]
mask = { bg = "#3c3836" }        # dark1
cand = { fg = "#458588" }        # neutral_blue
rest = { fg = "#928374" }        # gray
desc = { fg = "#fe8019" }        # neutral_orange
separator = "  "
separator_style = { fg = "#504945" }  # dark4
# : }}}

# : Help {{{
[help]
on = { fg = "#b8bb26" }      # neutral_green
off = { fg = "#fb4934" }     # neutral_red
exec = { fg = "#458588" }    # neutral_blue
desc = { fg = "#928374" }    # gray
hovered = { bg = "#504945", bold = true }  # dark4
footer = { fg = "#3c3836", bg = "#a89984" }  # dark1, light4
# : }}}

# : File-specific styles {{{
[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#458588" },  # neutral_blue

    # Videos
    { mime = "video/*", fg = "#b8bb26" },  # neutral_green
    { mime = "audio/*", fg = "#b8bb26" },  # neutral_green

    # Archives
    { mime = "application/zip",             fg = "#fe8019" },  # neutral_orange
    { mime = "application/gzip",            fg = "#fe8019" },
    { mime = "application/x-tar",           fg = "#fe8019" },
    { mime = "application/x-bzip",          fg = "#fe8019" },
    { mime = "application/x-bzip2",         fg = "#fe8019" },
    { mime = "application/x-7z-compressed", fg = "#fe8019" },
    { mime = "application/x-rar",           fg = "#fe8019" },

    # Fallback
    { name = "*", fg = "#a89984" },   # light4
    { name = "*/", fg = "#458588" }  # neutral_blue
]
# : }}}
